###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, TypeVar, Union, TypedDict, Type, Literal, cast
from typing_extensions import NotRequired
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types
from .types import Checked, Check
from .type_builder import TypeBuilder
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


OutputType = TypeVar('OutputType')


# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]

class BamlAsyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client


    
    async def CheckPageHasTransactions(
        self,
        statement_page: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.PageHasTransactions:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "CheckPageHasTransactions",
        {
          "statement_page": statement_page,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.PageHasTransactions, raw.cast_to(types, types))
    
    async def ExtractFinancialSummaryData(
        self,
        statements: Union[List[baml_py.Image], List[str]],
        baml_options: BamlCallOptions = {},
    ) -> types.FinancialSummary:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ExtractFinancialSummaryData",
        {
          "statements": statements,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.FinancialSummary, raw.cast_to(types, types))
    
    async def ExtractStatementPageTransactions(
        self,
        statement_page: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> List[types.Transaction]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ExtractStatementPageTransactions",
        {
          "statement_page": statement_page,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(List[types.Transaction], raw.cast_to(types, types))
    
    async def Hi(
        self,
        input: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "Hi",
        {
          "input": input,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(str, raw.cast_to(types, types))
    


class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def CheckPageHasTransactions(
        self,
        statement_page: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.PageHasTransactions, types.PageHasTransactions]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "CheckPageHasTransactions",
        {
          "statement_page": statement_page,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.PageHasTransactions, types.PageHasTransactions](
        raw,
        lambda x: cast(partial_types.PageHasTransactions, x.cast_to(types, partial_types)),
        lambda x: cast(types.PageHasTransactions, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractFinancialSummaryData(
        self,
        statements: Union[List[baml_py.Image], List[str]],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.FinancialSummary, types.FinancialSummary]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ExtractFinancialSummaryData",
        {
          "statements": statements,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.FinancialSummary, types.FinancialSummary](
        raw,
        lambda x: cast(partial_types.FinancialSummary, x.cast_to(types, partial_types)),
        lambda x: cast(types.FinancialSummary, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractStatementPageTransactions(
        self,
        statement_page: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[List[partial_types.Transaction], List[types.Transaction]]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ExtractStatementPageTransactions",
        {
          "statement_page": statement_page,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[List[partial_types.Transaction], List[types.Transaction]](
        raw,
        lambda x: cast(List[partial_types.Transaction], x.cast_to(types, partial_types)),
        lambda x: cast(List[types.Transaction], x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def Hi(
        self,
        input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[Optional[str], str]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "Hi",
        {
          "input": input,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[Optional[str], str](
        raw,
        lambda x: cast(Optional[str], x.cast_to(types, partial_types)),
        lambda x: cast(str, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    

b = BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]